Blockstream/green_cli

README.md

See 028ae4cdb8d300afec440ce09d86444175563a2d

Fix example of `set mnemonic` in README.md

---

green_cli/green.py

Better control over logging levels, also forward logging level to gdk

Support --log-level

---

.gitlab-ci.yml
.travis.yml
green_cli/green.py

Fixes https://github.com/Blockstream/green_cli/issues/19
Also update the CI images which were recently rebuilt.

Remove deleted gdk functions encrypt/decrypt

---

requirements-wally.txt

Install wally from PyPI

---

green_cli/common.py
requirements.txt

Replaces renamesubaccount since that is deprecated now.

Expose updatesubaccount

---

green_cli/liquid.py

Disable the tx command for liquid

---

green_cli/authenticators/__init__.py
green_cli/authenticators/default.py
green_cli/authenticators/watchonly.py
green_cli/decorators.py
requirements.txt

Requires the corresponding gdk release before merging.

Use the unified gdk login call GA_login_user

---

green_cli/gdk_resolve.py

Per the about-to-be-documented gdk HW interface.

Use the presence of "required_data" to drive HWW resolving

---

green_cli/common.py

Add --expired-at to getunspentoutputs command

---

green_cli/common.py
green_cli/tx.py
green_cli/utils.py

For fetching non-wallet transactions

Expose gettransactiondetails

---

green_cli/common.py

Add new filter options to getbalance/getunspentoutputs

---

green_cli/authenticators/__init__.py
green_cli/authenticators/wally.py

Requires the associated gdk changes

Update resolver to handle new gdk interface changes

---

green_cli/context.py
green_cli/green.py
green_cli/liquid.py

All Electrum Liquid sessions to available options, and allow overriding the Electrum server to connect to.

Single sig options

---

green_cli/common.py
green_cli/context.py
green_cli/green.py
green_cli/session.py

WIP: Requires upcoming gdk networking changes to be merged.
Updates cli to the latest networking ABI, and adds the `httprequest` action from https://github.com/Blockstream/green_cli/pull/76.

WIP: Update to latest gdk networking changes

---

README.md
green_cli/authenticators/jade.py
green_cli/common.py
green_cli/green.py
requirements-jade.txt

Support for Blockstream Jade HWW

Jade integration

---

requirements.txt

Once acked I will then merge `develop` to `master`.

Update gdk to release 0.0.54

---

README.md
green_cli/liquid.py
green_cli/tx.py

Those fields will be removed in GDK

Do not use "user_signed" and "server_signed"

---

green_cli/authenticators/jade.py
green_cli/authenticators/wally.py
green_cli/liquid.py
green_cli/tx.py

Various updates/new features for constructing partial transactions (i.e. swaps) via the `tx` interface.

Updates for swaps

---

green_cli/authenticators/jade.py

Send extra fields required for swaps tx (initial/partial and complete).

swaps jade: add Jade support for swap transactions

---

green_cli/authenticators/hardware.py
green_cli/authenticators/jade.py
green_cli/authenticators/wally.py

Let GDK handle the conversion internally

Do not use "create_recoverable_sig"

---

green_cli/authenticators/jade.py

Pass any `asset_blind_proof` if present in jade commitment data - same for `value_blind_proof`.

jade: pass any explicit asset/value proofs in commitment data

---

.gitlab-ci.yml
green_cli/common.py
green_cli/decorators.py
green_cli/liquid.py
green_cli/notifications.py
green_cli/twofa.py
green_cli/tx.py
requirements.txt

Requires the gdk 0.69.0 release before merging.

new develop branch targeting gdk 0.69.0

---

green_cli/authenticators/__init__.py
green_cli/authenticators/jade.py
green_cli/common.py
green_cli/decorators.py
green_cli/gdk_resolve.py
green_cli/green.py
green_cli/liquid.py
green_cli/session.py
green_cli/twofa.py
green_cli/tx.py
green_cli/utils.py
setup.py

deps: change gdk name

---

green_cli/common.py

Update to the new gdk interface for creating watch only users.

setwatchonly/disablewatchonly: use register_user
